# Generated by Django 4.2 on 2026-02-02 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_updated_at_profilechangelog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profilechangelog',
            options={'ordering': ['-changed_at'], 'verbose_name': 'Лог изменений', 'verbose_name_plural': 'Логи изменений'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterField(
            model_name='profilechangelog',
            name='changed_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата изменения'),
        ),
        migrations.AlterField(
            model_name='profilechangelog',
            name='field_name',
            field=models.CharField(max_length=255, verbose_name='Поле'),
        ),
        migrations.AlterField(
            model_name='profilechangelog',
            name='new_value',
            field=models.TextField(blank=True, null=True, verbose_name='Новое значение'),
        ),
        migrations.AlterField(
            model_name='profilechangelog',
            name='old_value',
            field=models.TextField(blank=True, null=True, verbose_name='Старое значение'),
        ),
        migrations.AlterField(
            model_name='profilechangelog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_logs', to='users.user', verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='user',
            name='about',
            field=models.TextField(blank=True, null=True, verbose_name='О себе'),
        ),
        migrations.AlterField(
            model_name='user',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='user',
            name='certificate_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ФИ для сертификата'),
        ),
        migrations.AlterField(
            model_name='user',
            name='channel_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Канал'),
        ),
        migrations.AlterField(
            model_name='user',
            name='chat_id',
            field=models.CharField(max_length=255, unique=True, verbose_name='ID чата'),
        ),
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='user',
            name='classic_rating',
            field=models.FloatField(blank=True, null=True, verbose_name='Рейтинг (классический)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='company',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Компания'),
        ),
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='important_info',
            field=models.TextField(blank=True, null=True, verbose_name='Дополнительная информация'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='user',
            name='position',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='user',
            name='quick_rating',
            field=models.FloatField(blank=True, null=True, verbose_name='Рейтинг (быстрый)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('player', 'Игрок'), ('voter', 'Судья'), ('viewer', 'Зритель'), ('adviser', 'Секундант'), ('admin', 'Администратор')], default='player', max_length=20, verbose_name='Роль'),
        ),
        migrations.AlterField(
            model_name='user',
            name='school',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Школа/Клуб'),
        ),
        migrations.AlterField(
            model_name='user',
            name='team_rating',
            field=models.FloatField(blank=True, null=True, verbose_name='Рейтинг (команда)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='telegram_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Telegram ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Telegram username'),
        ),
    ]
