# Generated by Django 4.2 on 2026-02-03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profilechangelog_options_alter_user_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationOutbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(max_length=255, verbose_name='ID чата (Telegram)')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], db_index=True, default='pending', max_length=16, verbose_name='Статус')),
                ('attempts', models.PositiveIntegerField(default=0, verbose_name='Попыток')),
                ('last_error', models.TextField(blank=True, null=True, verbose_name='Последняя ошибка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Отправлено')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_outbox', to='users.user', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Outbox уведомлений',
                'verbose_name_plural': 'Outbox уведомлений',
                'db_table': 'users_notificationoutbox',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='notificationoutbox',
            index=models.Index(fields=['status', 'created_at'], name='users_noti_status_7aaf0a_idx'),
        ),
    ]

