# Generated by Django 4.2 on 2026-02-03 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0003_votertimeslot_and_more'),
        ('users', '0004_notificationoutbox'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('player', 'Игрок'), ('voter', 'Судья'), ('viewer', 'Зритель'), ('adviser', 'Секундант'), ('admin', 'Администратор')], max_length=20, verbose_name='Роль участника')),
                ('status', models.CharField(choices=[('pending', 'Ожидание'), ('approved', 'Одобрена'), ('rejected', 'Отклонена')], db_index=True, default='pending', max_length=16, verbose_name='Статус заявки')),
                ('user_first_name', models.CharField(max_length=255, verbose_name='Имя (снимок)')),
                ('user_last_name', models.CharField(max_length=255, verbose_name='Фамилия (снимок)')),
                ('user_email', models.EmailField(max_length=254, verbose_name='Email (снимок)')),
                ('user_phone', models.CharField(max_length=20, verbose_name='Телефон (снимок)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата заявки')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата рассмотрения')),
                ('rejection_reason', models.TextField(blank=True, null=True, verbose_name='Причина отклонения')),
            ],
            options={
                'verbose_name': 'Заявка на регистрацию',
                'verbose_name_plural': 'Заявки на регистрацию',
                'db_table': 'users_registrationrequest',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='notificationoutbox',
            new_name='users_notif_status_9d7f7b_idx',
            old_name='users_noti_status_7aaf0a_idx',
        ),
        migrations.AddField(
            model_name='registrationrequest',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registration_requests', to='competitions.competition', verbose_name='Соревнование'),
        ),
        migrations.AddField(
            model_name='registrationrequest',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_registration_requests', to='users.user', verbose_name='Рассмотрено'),
        ),
        migrations.AddField(
            model_name='registrationrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registration_requests', to='users.user', verbose_name='Пользователь'),
        ),
        migrations.AddIndex(
            model_name='registrationrequest',
            index=models.Index(fields=['competition', 'status'], name='users_regis_competi_1f9a15_idx'),
        ),
        migrations.AddIndex(
            model_name='registrationrequest',
            index=models.Index(fields=['status', 'created_at'], name='users_regis_status_a18639_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='registrationrequest',
            unique_together={('user', 'competition', 'role')},
        ),
    ]
