# Generated by Django 4.2 on 2026-02-02 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('entry_open_player', models.BooleanField(default=True)),
                ('entry_open_voter', models.BooleanField(default=True)),
                ('entry_open_viewer', models.BooleanField(default=True)),
                ('entry_open_adviser', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('advisers', models.ManyToManyField(blank=True, related_name='competitions_as_adviser', to='users.user')),
                ('arbitrators', models.ManyToManyField(blank=True, related_name='competitions_as_arbitrator', to='users.user')),
                ('viewers', models.ManyToManyField(blank=True, related_name='competitions_as_viewer', to='users.user')),
                ('voters', models.ManyToManyField(blank=True, related_name='competitions_as_voter', to='users.user')),
            ],
            options={
                'db_table': 'competitions_competition',
            },
        ),
    ]
