# Generated by Django 4.2 on 2026-02-02 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profilechangelog_options_alter_user_options_and_more'),
        ('competitions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='competition',
            options={'verbose_name': 'Соревнование', 'verbose_name_plural': 'Соревнования'},
        ),
        migrations.AlterField(
            model_name='competition',
            name='advisers',
            field=models.ManyToManyField(blank=True, related_name='competitions_as_adviser', to='users.user', verbose_name='Секунданты'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='arbitrators',
            field=models.ManyToManyField(blank=True, related_name='competitions_as_arbitrator', to='users.user', verbose_name='Игроки'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='entry_open_adviser',
            field=models.BooleanField(default=True, verbose_name='Открыта регистрация (Секунданты)'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='entry_open_player',
            field=models.BooleanField(default=True, verbose_name='Открыта регистрация (Игроки)'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='entry_open_viewer',
            field=models.BooleanField(default=True, verbose_name='Открыта регистрация (Зрители)'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='entry_open_voter',
            field=models.BooleanField(default=True, verbose_name='Открыта регистрация (Судьи)'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='viewers',
            field=models.ManyToManyField(blank=True, related_name='competitions_as_viewer', to='users.user', verbose_name='Зрители'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='voters',
            field=models.ManyToManyField(blank=True, related_name='competitions_as_voter', to='users.user', verbose_name='Судьи'),
        ),
    ]
