# Generated by Django 4.2 on 2026-02-03 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_notificationoutbox'),
        ('competitions', '0002_alter_competition_options_alter_competition_advisers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoterTimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_date', models.DateField(verbose_name='Дата слота')),
                ('start_time', models.TimeField(verbose_name='Время начала')),
                ('end_time', models.TimeField(verbose_name='Время окончания')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voter_time_slots', to='competitions.competition', verbose_name='Соревнование')),
                ('voter', models.ForeignKey(limit_choices_to={'role': 'voter'}, on_delete=django.db.models.deletion.CASCADE, related_name='voter_time_slots', to='users.user', verbose_name='Судья')),
            ],
            options={
                'verbose_name': 'Временной слот судьи',
                'verbose_name_plural': 'Временные слоты судей',
                'db_table': 'competitions_votertimeslot',
                'ordering': ['slot_date', 'start_time'],
            },
        ),
        migrations.AddIndex(
            model_name='votertimeslot',
            index=models.Index(fields=['competition', 'slot_date'], name='competition_competi_22dddd_idx'),
        ),
        migrations.AddIndex(
            model_name='votertimeslot',
            index=models.Index(fields=['voter', 'competition'], name='competition_voter_i_ef6e2a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='votertimeslot',
            unique_together={('voter', 'competition', 'slot_date', 'start_time', 'end_time')},
        ),
    ]
